AWSTemplateFormatVersion: '2010-09-09'
Description: Amplify Template for Hugo Static Hosting

Parameters:

  Domain:
    Type: String
    Description: Domain name to host application

  Repository:
    Type: String
    Description: GitHub Repo with the Hugo Archive

  pSecretName:
    Type: String
    Description: Location of the GitHub Personal AccessToken

  pHostedZoneId:
    Type: String
    Description: Hosted Zone ID to update. Leave as NONE to skip.
    Default: NONE

  pPreviewUsername:
    Type: String

  pPreviewPassword:
    Type: String
    NoEcho: True

Conditions:
  UpdateRoute53: !Not [!Equals [ !Ref pHostedZoneId, "NONE"]]

Resources:

  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: amplify:*
                Resource: '*'
              - Effect: Allow
                Action: ssm:GetParameter
                Resource: '*'

  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      Name: !Sub ${Domain}-amplifyapp
      AccessToken: !Sub "{{resolve:secretsmanager:${pSecretName}:SecretString:github_pat}}"
      # AutoBranchCreationConfig:
      #   AutoBranchCreationConfig
      # BasicAuthConfig:
      #   BasicAuthConfig
      BuildSpec: |
        version: 1
        frontend:
          phases:
            build:
              commands:
                - wget --quiet https://github.com/gohugoio/hugo/releases/download/v0.111.1/hugo_extended_0.111.1_Linux-64bit.tar.gz
                - tar --overwrite -xf hugo_extended_0.111.1_Linux-64bit.tar.gz hugo
                - mv hugo /usr/bin/hugox
                - rm -rf hugo_extended_0.111.1_Linux-64bit.tar.gz
                - hugox version
                - hugox
          artifacts:
            baseDirectory: public
            files:
              - '**/*'
          cache:
            paths: []
      CustomRules:
        - Source: !Sub "https://${Domain}"
          Target: !Sub "https://www.${Domain}"
          Status: "302"
        - Source: "/<*>"
          Target: "/index.html"
          Status: "404"
      Description: !Ref Domain
      # EnableBranchAutoDeletion: Boolean
      # OauthToken: !Sub "{{resolve:secretsmanager:${pSecretName}:SecretString:github}}"
      Repository: !Ref Repository


  MainAmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: main
      AppId: !GetAtt AmplifyApp.AppId
      EnableAutoBuild: true
      Stage: PRODUCTION

  PreviewAmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: preview
      AppId: !GetAtt AmplifyApp.AppId
      EnableAutoBuild: true
      Stage: PRODUCTION
      BasicAuthConfig:
        EnableBasicAuth: true
        Username: !Ref pPreviewUsername
        Password: !Ref pPreviewPassword


  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      DomainName: !Ref Domain
      AppId: !GetAtt AmplifyApp.AppId
      SubDomainSettings:
        - BranchName: !GetAtt MainAmplifyBranch.BranchName
          Prefix: 'www'
        - BranchName: !GetAtt PreviewAmplifyBranch.BranchName
          Prefix: 'preview'


  # Not needed. Amplify will do this if it can
  # DomainValidationRecordSet:
  #   Type: AWS::Route53::RecordSet
  #   Condition: UpdateRoute53
  #   Properties:
  #     HostedZoneId: !Ref pHostedZoneId
  #     Name: !Select [0, !Split [' ', !GetAtt AmplifyDomain.CertificateRecord ] ]
  #     ResourceRecords:
  #       - !Select [2, !Split [' ', !GetAtt AmplifyDomain.CertificateRecord ] ]
  #     Type: CNAME
  #     TTL: 60


  # PublicRecordSet:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref pHostedZoneId
  #     Name: !Ref Domain
  #     AliasTarget:
  #       DNSName: !GetAtt CloudFrontDistro.DomainName
  #       HostedZoneId: Z2FDTNDATAQYW2 # Static value
  #     # ResourceRecords:
  #     #   - !GetAtt CloudFrontDistro.DomainName
  #     # TTL: 60
  #     Type: A

Outputs:
  CertificateRecord:
    Description: Certificate Record to validate the domain
    Value: !GetAtt AmplifyDomain.CertificateRecord
  AmplifyCertDomain:
    Value: !Select [0, !Split [' ', !GetAtt AmplifyDomain.CertificateRecord ] ]
  AmplifyCertRecord:
    Value: !Select [2, !Split [' ', !GetAtt AmplifyDomain.CertificateRecord ] ]
  AmplifyAppId:
    Value: !Ref AmplifyApp
  AmplifyDomainName:
    Value: !GetAtt AmplifyDomain.DomainName
  AmplifyDefaultDomain:
    Value: !GetAtt AmplifyApp.DefaultDomain
